services:
  - type: web
    name: tentation-lusitane
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASS_HASH
        sync: false
      - key: SESSION_SECRET
        sync: false
